name: Compile with SourceMod

on:
  push:
    branches: ["master", "serverKeywords"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sm_version: ["1.10", "1.11"]


    steps:
      - uses: actions/checkout@v1

      - name: Set environment variables
        run: |
          SOURCEMOD_PATH=$GITHUB_WORKSPACE/addons/sourcemod
          echo ::set-env name=SOURCEMOD_PATH::$SOURCEMOD_PATH
          echo ::set-env name=SCRIPTS_PATH::$SOURCEMOD_PATH/scripting

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION }}

      - name: Compile plugin
        run: |
          echo -e "\nCompiling mvotes.sp..."
          spcomp -E -w234 -O2 -v2 -i $SCRIPTS_PATH/include mvotes.sp
        working-directory: ${{ env.SCRIPTS_PATH }}/